openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:9000
  description: Generated server url
paths:
  /v1/articles/{articleId}:
    get:
      tags:
      - article-controller
      operationId: read
      parameters:
      - name: articleId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ArticleResponse"
    put:
      tags:
      - article-controller
      operationId: update
      parameters:
      - name: articleId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ArticleUpdateRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ArticleResponse"
    delete:
      tags:
      - article-controller
      operationId: delete
      parameters:
      - name: articleId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
  /v1/articles:
    get:
      tags:
      - article-controller
      operationId: readAll
      parameters:
      - name: boardId
        in: query
        required: true
        schema:
          type: integer
          format: int64
      - name: page
        in: query
        required: true
        schema:
          type: integer
          format: int64
      - name: pageSize
        in: query
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ArticlePageResponse"
    post:
      tags:
      - article-controller
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ArticleCreateRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ArticleResponse"
  /v1/articles/infinite-scroll:
    get:
      tags:
      - article-controller
      operationId: readAllInfiniteScroll
      parameters:
      - name: boardId
        in: query
        required: true
        schema:
          type: integer
          format: int64
      - name: pageSize
        in: query
        required: true
        schema:
          type: integer
          format: int64
      - name: lastArticleId
        in: query
        required: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ArticleResponse"
  /v1/articles/boards/{boardId}/count:
    get:
      tags:
      - article-controller
      operationId: count
      parameters:
      - name: boardId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: integer
                format: int64
components:
  schemas:
    ArticleUpdateRequest:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
    ArticleResponse:
      type: object
      properties:
        articleId:
          type: integer
          format: int64
        title:
          type: string
        content:
          type: string
        boardId:
          type: integer
          format: int64
        writerId:
          type: integer
          format: int64
        createdAt:
          type: string
          format: date-time
        modifiedAt:
          type: string
          format: date-time
    ArticleCreateRequest:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
        writerId:
          type: integer
          format: int64
        boardId:
          type: integer
          format: int64
    ArticlePageResponse:
      type: object
      properties:
        articles:
          type: array
          items:
            $ref: "#/components/schemas/ArticleResponse"
        articleCount:
          type: integer
          format: int64
