openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:9003
  description: Generated server url
paths:
  /v1/article-views/articles/{articleId}/users/{userId}:
    post:
      tags:
      - article-view-controller
      operationId: increase
      parameters:
      - name: articleId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: integer
                format: int64
  /v1/article-views/articles/{articleId}/count:
    get:
      tags:
      - article-view-controller
      operationId: count
      parameters:
      - name: articleId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: integer
                format: int64
components: {}
